---

- name: Install GitLab
  ansible.builtin.include_role:
    name: ocp4_workload_gitops_gitlab
  vars:
    ocp4_workload_gitops_gitlab_gitops_type: "{{ ocp4_workload_platform_engineering_workshop_gitlab_gitops_type }}"
    ocp4_workload_gitops_gitlab_config_email_display_name: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_email_display_name }}"
    ocp4_workload_gitops_gitlab_config_email_reply_to: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_email_reply_to }}"
    ocp4_workload_gitops_gitlab_config_smtp_enabled: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_smtp_enabled }}"
    ocp4_workload_gitops_gitlab_config_smtp_domain: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_smtp_domain }}"
    ocp4_workload_gitops_gitlab_config_smtp_port: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_smtp_port }}"
    ocp4_workload_gitops_gitlab_config_smtp_user: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_smtp_user }}"
    ocp4_workload_gitops_gitlab_config_smtp_password: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_smtp_password }}"
    ocp4_workload_gitops_gitlab_config_ssh_port: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_ssh_port }}"
    ocp4_workload_gitops_gitlab_config_rootPassword: "{{ common_password }}"
    ocp4_workload_gitops_gitlab_config_https: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_https }}"
    ocp4_workload_gitops_gitlab_config_root_email: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_root_email }}"
    ocp4_workload_gitops_gitlab_config_keybase_db: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_keybase_db }}"
    ocp4_workload_gitops_gitlab_config_keybase_otp: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_keybase_otp }}"
    ocp4_workload_gitops_gitlab_config_keybase_secret: "{{ ocp4_workload_platform_engineering_workshop_gitlab_config_keybase_secret }}"

    ocp4_workload_gitops_gitlab_db_user_name: "{{ ocp4_workload_platform_engineering_workshop_gitlab_db_user_name }}"
    ocp4_workload_gitops_gitlab_db_password: "{{ ocp4_workload_platform_engineering_workshop_gitlab_db_password }}"
    ocp4_workload_gitops_gitlab_db_name: "{{ ocp4_workload_platform_engineering_workshop_gitlab_db_name }}"

    ocp4_workload_gitops_gitlab_gitops_repo: "{{ ocp4_workload_platform_engineering_workshop_gitlab_gitops_repo }}"

    ocp4_workload_gitops_gitlab_import_repos: "{{ ocp4_workload_platform_engineering_workshop_gitlab_import_repos }}"

    ocp4_workload_gitops_gitlab_users_count: "{{ num_users | default(1) }}"
    ocp4_workload_gitops_gitlab_users_password: "{{ common_password }}"
