---

- name: Create namespace openshift-storage
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: openshift-storage

- name: Create OperatorGroup
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'noobaa/operatorgroup.yaml.j2') | from_yaml }}"

- name: Create operator subscription
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'noobaa/subscription.yaml.j2') | from_yaml }}"
  vars:
    install_operator_name: "{{ ocp4_workload_platform_engineering_workshop_noobaa_operator_name }}"
    install_operator_packagemanifest_name: "{{ ocp4_workload_platform_engineering_workshop_noobaa_operator_name }}"
    install_operator_namespace: "{{ ocp4_workload_platform_engineering_workshop_noobaa_operator_namespace }}"
    install_operator_channel: "{{ ocp4_workload_platform_engineering_workshop_noobaa_operator_channel }}"
    install_operator_automatic_install_plan_approval: "{{ ocp4_workload_platform_engineering_workshop_noobaa_operator_automatic_install_plan_approval }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_platform_engineering_workshop_noobaa_operator_use_catalog_snapshot }}"
    install_operator_catalog: "{{ ocp4_workload_platform_engineering_workshop_noobaa_operator_catalog }}"
    install_operator_starting_csv: "{{ ocp4_workload_platform_engineering_workshop_noobaa_operator_starting_csv }}"

- name: Create NooBaa instance
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'noobaa/noobaa.yaml.j2') | from_yaml }}"
