---

- name: Install OpenShift Pipelines
  ansible.builtin.include_role:
    name: ocp4_workload_pipelines
  vars:
    ocp4_workload_pipelines_channel: "{{ ocp4_workload_platform_engineering_workshop_pipelines_channel }}"
    ocp4_workload_pipelines_csv_nameprefix: "{{ ocp4_workload_platform_engineering_workshop_pipelines_csv_nameprefix }}"
    ocp4_workload_pipelines_use_catalog_snapshot: "{{ ocp4_workload_platform_engineering_workshop_pipelines_use_catalog_snapshot }}"
    ocp4_workload_pipelines_catalog_snapshot_image: "{{ ocp4_workload_platform_engineering_workshop_pipelines_catalog_snapshot_image }}"
    ocp4_workload_pipelines_catalog_snapshot_image_tag: "{{ cp4_workload_platform_engineering_workshop_pipelines_catalog_snapshot_image_tag }}"
