---

- name: Install Trusted Application Pipeline
  ansible.builtin.include_role:
    name: ocp4_workload_trusted_application_pipeline
  vars:
    ocp4_workload_trusted_application_pipeline_gitlab_root_password: "{{ common_password }}"
    ocp4_workload_trusted_application_pipeline_janus_bootstrap_repo: "{{ ocp4_workload_platform_engineering_workshop_tap_janus_bootstrap_repo }}"
    ocp4_workload_trusted_application_pipeline_janus_bootstrap_repo_target_revision:
      "{{ ocp4_workload_platform_engineering_workshop_tap_janus_bootstrap_repo_target_revision }}"
    # ocp4_workload_trusted_application_pipeline_backstage_gitlab_user_create:
    #   "{{ ocp4_workload_platform_engineering_workshop_tap_backstage_gitlab_user_create }}"
    # ocp4_workload_trusted_application_pipeline_backstage_gitlab_user_username: "{{ ocp4_workload_gitops_gitlab_user_username | default(omit) }}"
    # ocp4_workload_trusted_application_pipeline_backstage_gitlab_user_password: "{{ ocp4_workload_gitops_gitlab_user_password }}"
    ocp4_workload_trusted_application_pipeline_admin_user: "{{ ocp4_workload_platform_engineering_workshop_tap_admin_user }}"
    ocp4_workload_trusted_application_pipeline_admin_password: "{{ common_password }}"
    ocp4_workload_trusted_application_pipeline_gitlab_template_locations: "{{ ocp4_workload_platform_engineering_workshop_tap_gitlab_template_locations }}"

    ocp4_workload_trusted_application_pipeline_backstage_image: "{{ ocp4_workload_platform_engineering_workshop_tap_backstage_image }}"

    ocp4_workload_trusted_application_pipeline_users_count: "{{ ocp4_workload_platform_engineering_workshop_tap_users_count }}"
    ocp4_workload_trusted_application_pipeline_users_password: "{{ common_password }}"

    ocp4_workload_trusted_application_pipeline_backstage_helm_chart_repo: "{{ ocp4_workload_platform_engineering_workshop_tap_backstage_helm_chart_repo }}"
    ocp4_workload_trusted_application_pipeline_backstage_helm_chart: "{{ ocp4_workload_platform_engineering_workshop_tap_backstage_helm_chart }}"
    ocp4_workload_trusted_application_pipeline_backstage_helm_chart_version:
      "{{ ocp4_workload_platform_engineering_workshop_tap_backstage_helm_chart_version }}"
    ocp4_workload_trusted_application_pipeline_backstage_image_registry: "{{ ocp4_workload_platform_engineering_workshop_tap_backstage_image_registry }}"
    ocp4_workload_trusted_application_pipeline_backstage_image_repository: "{{ ocp4_workload_platform_engineering_workshop_tap_backstage_image_repository }}"
    ocp4_workload_trusted_application_pipeline_backstage_image_tag: "{{ ocp4_workload_platform_engineering_workshop_tap_backstage_image_tag }}"
    ocp4_workload_trusted_application_pipeline_docker_username: quayadmin
    ocp4_workload_trusted_application_pipeline_docker_password: "{{ common_password }}"

    ocp4_workload_trusted_application_pipeline_tpa_oidc_client_id: "{{ ocp4_workload_platform_engineering_workshop_tap_tpa_oidc_client_id }}"
    ocp4_workload_trusted_application_pipeline_tpa_oidc_client_secret: "{{ ocp4_workload_platform_engineering_workshop_tap_tpa_oidc_client_secret }}"
