---

- name: Install Trusted Profile Analyzer
  ansible.builtin.include_role:
    name: ocp4_workload_trusted_profile_analyzer
  vars:
    ocp4_workload_trusted_profile_analyzer_namespace: "{{ ocp4_workload_platform_engineering_workshop_tpa_namespace }}"
    ocp4_workload_trusted_profile_analyzer_minio_root_password: "{{ common_password }}"
    ocp4_workload_trusted_profile_analyzer_keycloak_admin_password: "{{ common_password }}"
    ocp4_workload_trusted_profile_analyzer_postgres_password: "{{ common_password }}"
    ocp4_workload_trusted_profile_analyzer_postgres_tpa_password: "{{ common_password }}"
    ocp4_workload_trusted_profile_analyzer_walker_client_secret: "{{ ocp4_workload_platform_engineering_workshop_tpa_walker_client_secret }}"
    ocp4_workload_trusted_profile_analyzer_testing_user_client_secret: "{{ ocp4_workload_platform_engineering_workshop_tpa_testing_user_client_secret }}"
    ocp4_workload_trusted_profile_analyzer_testing_manager_client_secret: "{{ ocp4_workload_platform_engineering_workshop_tpa_testing_manager_client_secret }}"
    ocp4_workload_trusted_profile_analyzer_guac_password: "{{ common_password }}"
    ocp4_workload_trusted_profile_analyzer_keycloak_realm_admin_password: "{{ common_password }}"
    ocp4_workload_trusted_profile_analyzer_install_repo_name: "{{ ocp4_workload_platform_engineering_workshop_tpa_install_repo_name }}"
    ocp4_workload_trusted_profile_analyzer_install_repo_branch: "{{ ocp4_workload_platform_engineering_workshop_tpa_install_repo_branch }}"
    ocp4_workload_trusted_profile_analyzer_install_repo_url: "{{ ocp4_workload_platform_engineering_workshop_tpa_install_repo_url }}"
    ocp4_workload_trusted_profile_analyzer_helm_chart_repo: "{{ ocp4_workload_platform_engineering_workshop_tpa_helm_chart_repo }}"
    ocp4_workload_trusted_profile_analyzer_helm_chart_name: "{{ ocp4_workload_platform_engineering_workshop_tpa_helm_chart_name }}"
    ocp4_workload_trusted_profile_analyzer_helm_chart_version: "{{ ocp4_workload_platform_engineering_workshop_tpa_helm_chart_version }}"
