---

- name: Install ODF
  ansible.builtin.include_tasks: openshift_data_foundation.yml

- name: Install ACM
  ansible.builtin.include_tasks: openshift_acm.yml

- name: Install RHDH Bootstrap
  ansible.builtin.include_tasks: redhat_developer_hub_bootstrap.yml
